# Generated by Django 4.2.7 on 2023-11-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_contactcard_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcard',
            name='location',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
